In [6]:
import numpy as np

In [9]:
li=[46,57,69]
np.array(li)

array([46, 57, 69])

In [12]:
li=np.array([2,4,6])
li

array([2, 4, 6])

In [24]:
lol=[[4,5,6,7],
     [7,8,9,0],
     [1,4,6,5]]
lol
#lol=matrix implementation

[[4, 5, 6, 7], [7, 8, 9, 0], [1, 4, 6, 5]]

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros(2,int)

array([0, 0])

In [19]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(3,5,6)

array([3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [31]:
np.random.rand(4)

array([0.82893842, 0.3627375 , 0.31589763, 0.02373792])

In [32]:
np.random.randint(3,15)

7

In [33]:
np.random.randint(20,56,100)

array([38, 23, 48, 25, 51, 24, 39, 54, 28, 51, 55, 22, 23, 45, 45, 53, 37,
       35, 51, 49, 26, 50, 44, 20, 32, 41, 23, 52, 44, 38, 39, 34, 23, 27,
       43, 44, 53, 54, 23, 32, 36, 20, 36, 26, 42, 49, 33, 54, 42, 35, 51,
       34, 25, 25, 41, 46, 54, 23, 34, 50, 32, 39, 48, 44, 45, 37, 48, 21,
       25, 26, 37, 25, 30, 49, 29, 39, 28, 22, 23, 53, 54, 25, 32, 29, 53,
       47, 41, 37, 49, 25, 22, 46, 24, 30, 31, 42, 26, 24, 49, 32])

In [34]:
samplearray=np.arange(40)
samplearray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [36]:
sample=np.arange(10,21)
sample

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
sample[1]

11

In [42]:
sample[2:5]

array([12, 13, 14])

In [43]:
sample[1:4]=100
sample

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [45]:
randarr=np.random.randint(0,100,20)
randarr

array([75, 65, 54, 56, 15, 31, 38, 20, 83, 94, 92, 71, 48, 25, 61, 16, 20,
       48, 80, 70])

In [49]:
randarr.reshape(4,5)


array([[75, 65, 54, 56, 15],
       [31, 38, 20, 83, 94],
       [92, 71, 48, 25, 61],
       [16, 20, 48, 80, 70]])

In [54]:
a=np.random.rand(4,5)
a

array([[0.30371406, 0.4654205 , 0.34730364, 0.88441408, 0.3949665 ],
       [0.39407471, 0.52928508, 0.03548035, 0.19519431, 0.20392041],
       [0.62341387, 0.96845832, 0.36105437, 0.9006797 , 0.3099968 ],
       [0.54406142, 0.36833877, 0.77746704, 0.25855594, 0.44256852]])

In [55]:
randarr.min()

15

In [56]:
randarr.max()

94

In [60]:
subsetsample=sample[1:7]
subsetsample

array([100, 100, 100,  14,  15,  16])

In [63]:
subsetsample[:]=1001
subsetsample

array([1001, 1001, 1001, 1001, 1001, 1001])

In [69]:
sample_matrix=np.array(([30,20,40],[9,45,36],[5,4,3])
                      )
sample_matrix

array([[30, 20, 40],
       [ 9, 45, 36],
       [ 5,  4,  3]])

In [70]:
sample_matrix[0][2
                ]

40

In [72]:
sample_matrix[2,:]


array([5, 4, 3])

In [73]:
sample_matrix[2]

array([5, 4, 3])

In [78]:
sample_matrix[:,(0,2)]

array([[30, 40],
       [ 9, 36],
       [ 5,  3]])

Selection Techniques

In [81]:
samplear=np.arange(1,21)
samplear

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
samplear.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [83]:
samplear+samplear

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [85]:
np.exp(samplear)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [86]:
np.sqrt(samplear)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])